name: run revenue calculator

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          pip install pandas

      - name: run revenue calculator
        run: |
          python revenue_calculator.py

      - name: commit dan push hasilnya ke repo
        run: |
          git config --global user.name ${{secrets.username}}
          git config --global user.email ${{secrets.email}}
          git add result_data.csv
          git commit -m 'file berhasil di-commit dan di-push ke repo'
          git push origin main
          echo "file berhasil di-commit dan di-push ke repo"